### PR TITLE
Update docs and support empty prop types

### LINKED ISSUE #11: Update docs and support empty `PropTypes`
1. Update the source prop docs to say `source={docgen.parse(require("!!raw!../src/components/ur-awsum-component"))`
2. Add support for empty PropTypes

### PR DESCRIPTION
**Pull request by coopy**
Fixes #11.

We now render a "missing PropTypes" message when the documented component is missing proptypes and defaults.

/cc @boygirl

### CODE REVIEW

**Comment by kenwheeler** [comment]
LGTM

**Comment by coopy** [comment]
Will check on the effect of bundle size before merging this.

**Comment by coopy** [comment]
Geez, sorry I left this open so long. Finally getting back to it.

**Comment by coopy** [comment]
This change has no effect on bundle size. It's still `ecology.min.js  1.13 MB`
I've logged this as a problem in https://github.com/FormidableLabs/ecology/issues/16

Edit: This change increases size by `104 bytes`.

**Pull request merged**
