### PR TITLE
Babel 6

### PR DESCRIPTION
**Pull request by NogsMPLS**
Ran all tests and demo site on a Windows 7 machine, Node 4.3.0 and npm 2.14.12.

### CODE REVIEW

**Comment by NogsMPLS** [comment]
donking @kenwheeler on the head

**Comment by kenwheeler** [comment]
@NogsMPLS Awesomesauce. Thanks so much dude!

**Comment by NogsMPLS** [comment]
:tada:

**Comment by kenwheeler** [comment]
@coopy do you want to cut the release or did you want me to?

**Comment by kenwheeler** [comment]
@coopy scratch that, ci shenanigans afoot. gonna debug locally.

**Comment by NogsMPLS** [comment]
oh nooooo! let me know what's up and I'll look into it

**Comment by kenwheeler** [comment]
@NogsMPLS .babelrc helps lol. We do a lib transpile as a build step, independent of webpack. Just pushed it up.

**Comment by NogsMPLS** [comment]
Oh dang, my bad!

**Comment by kenwheeler** [comment]
sall good, we green now

**Pull request merged**
